rule bwa_mem:
    input:
        reads=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"]
    output:
        "mapped/{sample}.bam"
    log:
        "logs/bwa_mem/{sample}.log"
    params:
        db_prefix="genome",
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sorting="none",             # Can be 'none', 'samtools' or 'picard'.
        sorting_order="queryname",  # Can be 'queryname' or 'coordinate'.
        sorting_extra=""            # Extra args for samtools/picard.
    threads: 8
    wrapper:
        "master/bio/bwa/mem"
